#!/bin/bash
sv start 01x11vnc || exit 1
export HOME="/home/user"
export DISPLAY=":1"
export USER="user"
echo sudo -E -u $USER /opt/google/chrome/chrome --user-data-dir  --disable-gpu-watchdog  \
    --window-position=0,0 --window-size=${XRFBRESX},${XRFBRESY} --force-device-scale-factor=1 \
    ${XRFBURI}
exec sudo -E -u $USER /opt/google/chrome/chrome --user-data-dir  --disable-gpu-watchdog  \
    --window-position=0,0 --window-size=${XRFBRESX},${XRFBRESY} --force-device-scale-factor=1 \
    ${XRFBURI}
