#!/bin/bash
sv start 02x11vnc || exit 1
export HOME="/home/chrome"
export DISPLAY=":1"
export USER="chrome"
exec sudo -E -u $USER /opt/google/chrome/chrome --user-data-dir  --window-position=0,0 --window-size=${XRFBRESX},${XRFBRESY} --force-device-scale-factor=1
